### ISSUE TITLE
Cloud Config?

### ISSUE THREAD

**Issue by rosenhouse** [Amit-PivotalLabs/bbl-cf-diego-bosh-2.0#1]
Would you mind sharing your cloud config yaml file that supports the `cf-manifest.yml` file here?

**Comment by yatzek-zz** [comment]
+1

**Comment by yatzek-zz** [comment]
@rosenhouse - have a look at this: 

https://github.com/pivotal-cf-experimental/bosh-bootloader/blob/master/bbl/fixtures/cloud-config-cf-elb.yml

should give you an idea what the cloud config should look like.

**Comment by rosenhouse** [comment]
Yup, this is now covered by the [bosh-bootloader](https://github.com/cloudfoundry/bosh-bootloader) and [cf-deployment](https://github.com/cloudfoundry/cf-deployment).
